# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: daemon-spawn 0.4.2 ruby lib

Gem::Specification.new do |s|
  s.name = "daemon-spawn"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alex Vollmer", "Seamus Abshere", "Emmanual Gomez", "Seth Falcon", "Woody Peterson", "Tilo Pr\u{fc}tz", "Kazuto Tominaga"]
  s.date = "2015-01-05"
  s.description = "With daemon-spawn you can start, stop and restart processes that run\n    in the background. Processed are tracked by a simple PID file written\n    to disk."
  s.email = "alex.vollmer@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "daemon-spawn.gemspec",
    "lib/daemon_spawn.rb",
    "test/daemon_spawn_test.rb",
    "test/multi_daemon_spawn_test.rb",
    "test/servers/deaf_server.rb",
    "test/servers/echo_server.rb",
    "test/servers/log_to_io_server.rb",
    "test/servers/logger_server.rb",
    "test/servers/simple_server.rb",
    "test/servers/stubborn_server.rb",
    "test/servers/taps_server.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/alexvollmer/daemon-spawn"
  s.rubyforge_project = "daemon-spawn"
  s.rubygems_version = "2.4.2"
  s.summary = "Daemon launching and management made dead simple"
end

